# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movie.proto',
  package='',
  serialized_pb=_b('\n\x0bmovie.proto\"8\n\x04\x44\x61te\x12\x0b\n\x03\x64\x61y\x18\x01 \x02(\x05\x12\x15\n\x05month\x18\x02 \x02(\x0e\x32\x06.Month\x12\x0c\n\x04year\x18\x03 \x02(\x05\"]\n\x06Review\x12\x1d\n\tuser_name\x18\x01 \x01(\t:\nAnnonymous\x12\x0e\n\x06rating\x18\x02 \x02(\x05\x12\x13\n\x04\x64\x61te\x18\x03 \x02(\x0b\x32\x05.Date\x12\x0f\n\x07\x63omment\x18\x04 \x03(\t\"\xc1\x03\n\x05Movie\x12\x0b\n\x03_id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1e\n\x0f\x64\x61te_of_release\x18\x03 \x02(\x0b\x32\x05.Date\x12\x1b\n\x05genre\x18\x04 \x02(\x0e\x32\x0c.Movie.Genre\x12\x10\n\x08\x64uration\x18\x05 \x02(\x05\x12\r\n\x05\x61\x63tor\x18\x06 \x03(\t\x12\x10\n\x08\x64irector\x18\x07 \x03(\t\x12\x17\n\x06review\x18\x08 \x03(\x0b\x32\x07.Review\"\x93\x02\n\x05Genre\x12\n\n\x06\x41\x43TION\x10\x01\x12\r\n\tADVENTURE\x10\x02\x12\r\n\tANIMATION\x10\x03\x12\r\n\tBIOGRAPHY\x10\x04\x12\n\n\x06\x43OMEDY\x10\x05\x12\t\n\x05\x43RIME\x10\x06\x12\x0f\n\x0b\x44OCUMENTARY\x10\x07\x12\t\n\x05\x44RAMA\x10\x08\x12\n\n\x06\x46\x41MILY\x10\t\x12\x0b\n\x07\x46\x41NTACY\x10\n\x12\r\n\tFILM_NOIR\x10\x0b\x12\x0b\n\x07HISTORY\x10\x0c\x12\n\n\x06HORROR\x10\r\x12\t\n\x05MUSIC\x10\x0e\x12\x0b\n\x07MUSICAL\x10\x0f\x12\x0b\n\x07ROMANCE\x10\x10\x12\n\n\x06SCI_FI\x10\x11\x12\t\n\x05SPORT\x10\x12\x12\x0b\n\x07TRILLER\x10\x13\x12\x07\n\x03WAR\x10\x14\x12\x0b\n\x07WESTERN\x10\x15*\x99\x01\n\x05Month\x12\x0b\n\x07JANUARY\x10\x01\x12\x0c\n\x08\x46\x45\x42RUARY\x10\x02\x12\t\n\x05MARCH\x10\x03\x12\t\n\x05\x41PRIL\x10\x04\x12\x07\n\x03MAY\x10\x05\x12\x08\n\x04JUNE\x10\x06\x12\x08\n\x04JULY\x10\x07\x12\n\n\x06\x41UGUST\x10\x08\x12\r\n\tSEPTEMBER\x10\t\x12\x0b\n\x07OCTOBER\x10\n\x12\x0c\n\x08NOVEMBER\x10\x0b\x12\x0c\n\x08\x44\x45\x43\x45MBER\x10\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MONTH = _descriptor.EnumDescriptor(
  name='Month',
  full_name='Month',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JANUARY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEBRUARY', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARCH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APRIL', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAY', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JUNE', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JULY', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUGUST', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEPTEMBER', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OCTOBER', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOVEMBER', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECEMBER', index=11, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=621,
  serialized_end=774,
)
_sym_db.RegisterEnumDescriptor(_MONTH)

Month = enum_type_wrapper.EnumTypeWrapper(_MONTH)
JANUARY = 1
FEBRUARY = 2
MARCH = 3
APRIL = 4
MAY = 5
JUNE = 6
JULY = 7
AUGUST = 8
SEPTEMBER = 9
OCTOBER = 10
NOVEMBER = 11
DECEMBER = 12


_MOVIE_GENRE = _descriptor.EnumDescriptor(
  name='Genre',
  full_name='Movie.Genre',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADVENTURE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANIMATION', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIOGRAPHY', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMEDY', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRIME', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOCUMENTARY', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAMA', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAMILY', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FANTACY', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILM_NOIR', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISTORY', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HORROR', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUSIC', index=13, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUSICAL', index=14, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROMANCE', index=15, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCI_FI', index=16, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPORT', index=17, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRILLER', index=18, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAR', index=19, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WESTERN', index=20, number=21,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=343,
  serialized_end=618,
)
_sym_db.RegisterEnumDescriptor(_MOVIE_GENRE)


_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='Date.day', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='month', full_name='Date.month', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='year', full_name='Date.year', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=71,
)


_REVIEW = _descriptor.Descriptor(
  name='Review',
  full_name='Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='Review.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Annonymous").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rating', full_name='Review.rating', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='Review.date', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='Review.comment', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=166,
)


_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='Movie._id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Movie.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_of_release', full_name='Movie.date_of_release', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genre', full_name='Movie.genre', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Movie.duration', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actor', full_name='Movie.actor', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='director', full_name='Movie.director', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='review', full_name='Movie.review', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOVIE_GENRE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=618,
)

_DATE.fields_by_name['month'].enum_type = _MONTH
_REVIEW.fields_by_name['date'].message_type = _DATE
_MOVIE.fields_by_name['date_of_release'].message_type = _DATE
_MOVIE.fields_by_name['genre'].enum_type = _MOVIE_GENRE
_MOVIE.fields_by_name['review'].message_type = _REVIEW
_MOVIE_GENRE.containing_type = _MOVIE
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Review'] = _REVIEW
DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE
DESCRIPTOR.enum_types_by_name['Month'] = _MONTH

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  ))
_sym_db.RegisterMessage(Date)

Review = _reflection.GeneratedProtocolMessageType('Review', (_message.Message,), dict(
  DESCRIPTOR = _REVIEW,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Review)
  ))
_sym_db.RegisterMessage(Review)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), dict(
  DESCRIPTOR = _MOVIE,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Movie)
  ))
_sym_db.RegisterMessage(Movie)


# @@protoc_insertion_point(module_scope)
